spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared


server:
  port: 8888

logging:
  level:
    root: INFO
    org.yyitsz: DEBUG
    org.springframework: INFO



