spring:
  application:
    name: auth-service
  cloud:
    config:
      #      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD:abc123}
      username: user
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO