@startuml
'https://plantuml.com/state-diagram

scale 750 width

PENDING:
PROCESSING:
SUCCESS:
FAILED:
REJECTED:
CANCELLED:

[*] --> PENDING
PENDING --> PROCESSING : Follow parent request (Approved or STP)
PROCESSING --> SUCCESS : Replied Success by CCASS
PROCESSING --> FAILED:  Replied failure by CCASS
PENDING --> REJECTED: Follow parent request(Rejected by user)
PENDING --> CANCELLED: Follow parent request(Cancelled by client)
SUCCESS --> [*]
REJECTED --> [*]
CANCELLED --> [*]
FAILED --> [*]

@enduml