spring:
  application:
    name: registry
#  cloud:
#    config:
#      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0