server:
  servlet:
    context-path: /accounts
  port: 7010

#example for feign
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      statistics-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
