server:
  servlet:
    context-path: /accounts
  port: 6000

#example for feign
feign::
  circuitbreaker:
    enabled: true
  client:
    config:
      statistics-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      feignName-example:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: #com.example.SimpleErrorDecoder
        retryer: #com.example.SimpleRetryer
        defaultQueryParameters:
          query: queryValue
          defaultRequestHeaders:
            header: headerValue
          requestInterceptors:
            - #com.example.FooRequestInterceptor
            - #com.example.BarRequestInterceptor
          decode404: false
          encoder: #com.example.SimpleEncoder
          decoder: #com.example.SimpleDecoder
          contract: #com.example.SimpleContract