spring:
  data:
    mongodb:
      #host: auth-mongodb
      host: 10.100.53.131
      username: user
      password: ${MONGODB_PASSWORD:abc123}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
