spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true #default
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:80"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
      actuator:
        verbose:
          enabled: true # default

      routes:
        - id: auth-service
          uri: lb://auth-service:5000
          predicates:
            - Path=/uaa/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/statistics/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 7030
