server:
  servlet:
    context-path: /statistics
  port: 7000

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      rates-client:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

rates:
  url: https://api2.exchangeratesapi.io