spring:
  application:
    name: account-service
  cloud:
    config:
      #      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD:abc123}
      username: user
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
          statistics-service:
            provider: spring
            client-id: statistics-service
            client-secret: password
            authorization-grant-type: client_credentials
            scope: server
            client-name: statistics-service
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: password
            authorization-grant-type: client_credentials
            scope: server
            client-name: notification-service
          account-service:
            provider: spring
            client-id: account-service
            client-secret: password
            authorization-grant-type: client_credentials
            scope: server
            client-name: account-service
        provider:
          spring:
            issuer-uri: http://127.0.0.1:7090/uaa